-- MySQL Script generated by MySQL Workbench
-- Mon Jan  1 07:04:31 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema myforum
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema myforum
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myforum` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `myforum` ;

-- -----------------------------------------------------
-- Table `myforum`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myforum`.`posts` (
  `post_id` INT NOT NULL AUTO_INCREMENT,
  `topic_id` INT NOT NULL,
  `title` VARCHAR(360) NOT NULL,
  `author_id` INT NOT NULL,
  `content` VARCHAR(10000) NULL DEFAULT NULL,
  `like_count` INT NOT NULL DEFAULT '0',
  `datetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`post_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `myforum`.`replies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myforum`.`replies` (
  `reply_id` INT NOT NULL AUTO_INCREMENT,
  `previous_id` INT NULL DEFAULT NULL,
  `content` VARCHAR(1000) NOT NULL,
  `likes` INT NOT NULL DEFAULT '0',
  `replied_to` TINYINT(1) NOT NULL DEFAULT '0',
  `datetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `post_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`reply_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `myforum`.`subscriptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myforum`.`subscriptions` (
  `user_id` INT NOT NULL,
  `topic_id` INT NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `myforum`.`topics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myforum`.`topics` (
  `topic_id` INT NOT NULL AUTO_INCREMENT,
  `topic_name` VARCHAR(45) NOT NULL,
  `topic_desc` VARCHAR(400) NULL DEFAULT NULL,
  PRIMARY KEY (`topic_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `myforum`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myforum`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(320) NULL DEFAULT NULL,
  `pass` VARCHAR(64) NULL DEFAULT NULL,
  `signup_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `myforum` ;

-- -----------------------------------------------------
-- Placeholder table for view `myforum`.`post_topics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myforum`.`post_topics` (`post_id` INT, `title` INT, `author_id` INT, `content` INT, `like_count` INT, `datetime` INT, `topic_name` INT, `topic_desc` INT, `topic_id` INT, `username` INT);

-- -----------------------------------------------------
-- procedure getComments
-- -----------------------------------------------------

DELIMITER $$
USE `myforum`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `getComments`(IN postID int)
BEGIN
    SELECT replies.*, users.username
    from replies
    JOIN users
    ON replies.user_id = users.user_id
    WHERE postID = replies.post_id
    
    ORDER by datetime ASC;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure getPostData
-- -----------------------------------------------------

DELIMITER $$
USE `myforum`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `getPostData`(IN postID INT)
BEGIN
	SELECT * FROM post_topics
    WHERE postID = post_id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure getPosts
-- -----------------------------------------------------

DELIMITER $$
USE `myforum`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `getPosts`(IN input_id INT)
BEGIN
	SELECT * FROM post_topics
    WHERE topic_id = input_id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure selectTopicByID
-- -----------------------------------------------------

DELIMITER $$
USE `myforum`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `selectTopicByID`(IN input_id INT)
BEGIN

SELECT * from topics where topic_id = input_id;
	
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure topTopics
-- -----------------------------------------------------

DELIMITER $$
USE `myforum`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `topTopics`()
BEGIN
Select topic_id, COUNT(topic_id) FROM subscriptions GROUP BY topic_id ORDER BY COUNT(topic_id) DESC;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure validateUser
-- -----------------------------------------------------

DELIMITER $$
USE `myforum`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `validateUser`(IN inputUser VARCHAR(20), IN inputPass VARCHAR(64))
BEGIN
SELECT * from users
WHERE inputUser = username && inputPass = pass;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- View `myforum`.`post_topics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myforum`.`post_topics`;
USE `myforum`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `myforum`.`post_topics` AS select `myforum`.`posts`.`post_id` AS `post_id`,`myforum`.`posts`.`title` AS `title`,`myforum`.`posts`.`author_id` AS `author_id`,`myforum`.`posts`.`content` AS `content`,`myforum`.`posts`.`like_count` AS `like_count`,`myforum`.`posts`.`datetime` AS `datetime`,`myforum`.`topics`.`topic_name` AS `topic_name`,`myforum`.`topics`.`topic_desc` AS `topic_desc`,`myforum`.`topics`.`topic_id` AS `topic_id`,`myforum`.`users`.`username` AS `username` from ((`myforum`.`posts` join `myforum`.`topics` on((`myforum`.`posts`.`topic_id` = `myforum`.`topics`.`topic_id`))) join `myforum`.`users` on((`myforum`.`posts`.`author_id` = `myforum`.`users`.`user_id`))) order by `myforum`.`posts`.`datetime` desc;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
